server:
  port: 9999


# wakatime 配置
wakatime:
  # 基础url
  base_url: https://wakatime.com/api/v1/
  # 密钥
  secret_api_key: 16e493aa-9ba5-4a40-bcd5-f105bf9522b6
  # 安全url
  oauth_url: https://wakatime.com/oauth/token/
  # 用户信息url
  user_info_url: ${wakatime.base_url}/users/current
  # xxx日期下的开发时间
  duration_url: ${wakatime.base_url}/users/current/durations
  # 心跳url
  heart_url: ${wakatime.base_url}/users/current/heartbeats
  # 当前用户的项目列表
  project_url: ${wakatime.base_url}/users/current/projects
  # 一定范围内的开发
  summary_url: ${wakatime.base_url}/users/current/summaries
  # 项目列表的commit时间
  project_detail: ${wakatime.base_url}/users/current/projects